from opr_battler.army_book import ArmyBook

armies: list[ArmyBook] = [
    {
        "uid": "w7qor7b2kuifcyvk",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Alien Hives",
        "genericName": "Alien Hives||Ar'Ksenos Hives||Ar'Ksenos Hives",
        "hint": "",
        "background": "The Alien Hives are a faction of aliens using biotechnology, made up of a variety of subspecies which come from the remote frontiers of the galaxy, hoping to recreate the Mother that shaped them.\n\nWhen they first arrived, they were viewed as monstrous invaders, but after a long war of extermination, breakthroughs in communication led to a fragile peace. Now, the Hives must come to terms with the legacy of the First Contact War and decide how they are to adapt.",
        "unitCount": 41,
        "modifiedAt": "2026-07-14T11:27:43.592Z",
        "editedAt": "2026-04-30T11:21:42.365Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/w7qor7b2kuifcyvk/e8NxW83dK3XOt-ULQYz9D.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/w7qor7b2kuifcyvk/p7by4vNjyUPewTct4_dxW.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "w7qor7b2kuifcyvk~2",
    },
    {
        "uid": "78qp9l5alslt6yj8",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Battle Brothers",
        "genericName": "Battle Brothers||Battleborn||Battleborn",
        "hint": "",
        "background": "The Battle Brothers are superhuman warriors that have been empowered through gene-mods and special training to bring about their Founder’s vision of an uplifted humanity. \n\nTheir pursuit of this vision at any cost led to a violent civil war which nearly destroyed humanity itself, and in pursuit of their enemies fleeing this conflict, they found themselves lost in the Sirius Sector. The Battle Brothers have not relented however, and they go to any length to unite and uplift all of humanity.",
        "unitCount": 26,
        "modifiedAt": "2026-07-14T11:27:43.623Z",
        "editedAt": "2026-06-18T09:33:24.034Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/78qp9l5alslt6yj8/kKAEn4ezTssljABfM5lu1.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": "Battle Brothers",
        "factionRelation": None,
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 5,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "78qp9l5alslt6yj8~2",
    },
    {
        "uid": "7oi8zeiqfamiur21",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Blessed Sisters",
        "genericName": "Blessed Sisters||Blessed Sisters||Blessed Vanguards",
        "hint": "",
        "background": "The Blessed Sisters are an elite force of religious warriors equipped with advanced armour and weaponry, which formed under the guidance of the God-Queen, a humble woman suddenly turned into a symbol of hope and resistance.\n\nThe sisterhoods act as mediators and rely on diplomacy rather than ruling through force. This has left them without the power and resources of other factions, dependent instead on an ever fragile web of alliances and donations.",
        "unitCount": 28,
        "modifiedAt": "2026-07-14T11:27:43.659Z",
        "editedAt": "2026-04-23T11:12:46.105Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7oi8zeiqfamiur21/QU7uSLU-BfYrTKv9D0e-J.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/7oi8zeiqfamiur21/RNJme63YpL4erTrjrTsZQ.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "7oi8zeiqfamiur21~2",
    },
    {
        "uid": "xnnqhh1775kvmz2r",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Blood Brothers",
        "genericName": "Blood Brothers||Blood Hawks||Blood Hawks",
        "hint": None,
        "background": "Battle Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 28,
        "modifiedAt": "2026-07-14T11:27:43.675Z",
        "editedAt": "2026-05-04T01:01:42.435Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/sgnt124CD6hqT4Qb/e2GozD-l5Lv1jkDPdM5Zs.jpg",
        "bannerImagePath": "",
        "visibility": 1,
        "factionId": "78qp9l5alslt6yj8",
        "factionName": "Battle Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 5,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "xnnqhh1775kvmz2r~2",
    },
    {
        "uid": "7ex2x15bpkmy1alv",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Blood Prime Brothers",
        "genericName": "Blood Prime Brothers||Prime Blood Hawks||Paragon Blood Hawks",
        "hint": None,
        "background": "Prime Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 32,
        "modifiedAt": "2026-07-14T11:27:43.692Z",
        "editedAt": "2025-12-02T11:37:26.940Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/w8345FpXEqcftWor/apd31cJ_hbJHE1t3DKFwo.jpg",
        "bannerImagePath": "",
        "visibility": 1,
        "factionId": "oqnnu0gk8q6hyyny",
        "factionName": "Prime Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "7ex2x15bpkmy1alv~2",
    },
    {
        "uid": "r6hr29338u4micfw",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Change Disciples",
        "genericName": "Change Disciples||Scions of Change||Scions of Ch'nanak",
        "hint": None,
        "background": "Havoc Disciples are Battle Brothers who have embraced the worship of a particular Havoc God. Individually powerful and resilient, each Havoc Disciple has been molded with unique blessings by the god they follow. \n\nStranded in the Sirius Sector, many Battle Brothers were scattered and left with little chance of survival. These desperate castaways were approached by different gods who offered powerful boons in exchange for their worship. Each god empowered their respective followers, reforging their Disciples according to their will. The Havoc Disciples are now torn between fanatical devotion to their new gods and maintaining their former discipline.",
        "unitCount": 25,
        "modifiedAt": "2026-07-14T11:27:43.724Z",
        "editedAt": "2026-03-31T19:57:54.431Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/TT9y-mP9fVUKA9_G/NleS5zRd-jKA6Y6fzBXIV.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "7o6om21wxlvvy3hq",
        "factionName": "Havoc Brothers",
        "factionRelation": "Disciples",
        "factionNameGeneric": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "r6hr29338u4micfw~2",
    },
    {
        "uid": "ewbra8nv3nq3k27p",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Custodian Brothers",
        "genericName": "Guardian Brothers||Guardian Brothers||Blessed Guardians",
        "hint": "",
        "background": "The Custodian Brothers are the personal protectors of the Conduit, the heir of the Founder who created the gene-mods. Few in number, they use cutting edge armour and weapons, customized to their exact specifications. \n\nThey serve as the Conduit’s personal guard and emissaries, delivering his orders and enforcing his will directly. The Custodians depend heavily upon their reputation and the trust that others invest in them. In order to maintain their status, they have slowly embraced intricate honour ceremonies, destructive rivalries and webs of lies and secrets.",
        "unitCount": 22,
        "modifiedAt": "2026-07-14T11:27:43.772Z",
        "editedAt": "2026-04-30T09:33:08.430Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/ewbra8nv3nq3k27p/Wn55S1LPYkkqOZQgkCP55.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "ewbra8nv3nq3k27p~2",
    },
    {
        "uid": "z8205ez2boggzs22",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "DAO Union",
        "genericName": "Battlesuit Empire||D.A.O.U.||D.A.O.U.",
        "hint": "",
        "background": "The DAO Union is a coalition of aliens equipped with advanced weapons and drones. Their armies rely on advanced ranged weaponry and mobility to keep enemies at bay.\n\nThose in the DAOU have embraced logic as the core of their society, rejecting selfish impulses. They came to depend upon machine logic to make sensible and impartial choices, which earned them a reputation as mediators in Sirius. It was only when this logic nearly resulted in their total redundancy that they began to question it. Rejecting AI, those in the DAOU now seek to build a better society for themselves.",
        "unitCount": 18,
        "modifiedAt": "2026-07-14T11:27:43.784Z",
        "editedAt": "2026-05-03T22:53:35.306Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/z8205ez2boggzs22/GtUpvYrlW3_U2CNAYWZIu.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "z8205ez2boggzs22~2",
    },
    {
        "uid": "xp5zwh73lg1uaym4",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Dark Brothers",
        "genericName": "Dark Brothers||Dark Bulls||Dark Bulls",
        "hint": None,
        "background": "Battle Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 27,
        "modifiedAt": "2026-07-14T11:27:43.798Z",
        "editedAt": "2026-04-27T16:49:29.245Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/Ssl_Zmird4I3rGX7/XP3K22YlLliHJHPM4WG_V.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "78qp9l5alslt6yj8",
        "factionName": "Battle Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 5,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "xp5zwh73lg1uaym4~2",
    },
    {
        "uid": "q11la9v8h1heu9ja",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Dark Elf Raiders",
        "genericName": "Dark Elves||Dark-Edge Elves||Dark-Edge Raiders",
        "hint": "",
        "background": "The Dark Elf Raiders are disparate gangs formed by surviving members of the underclass after the Elven Empire collapsed. They rely on the mobility of their small raiding parties and advanced anti-gravity skimmers to make up for their lack of heavy armor.\n\nAbandoned by their ruling class during the Robot Legion uprising, handfuls of the Elvish lower classes managed to escape into space. These surviving Elves formed gangs, ready to do whatever it takes to survive. Bitter and distrustful of outsiders, the Gangs persist, taking what they need from outsiders to ensure that they can never be betrayed again.",
        "unitCount": 26,
        "modifiedAt": "2026-07-14T11:27:43.814Z",
        "editedAt": "2026-04-27T16:55:56.062Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "army-books/covers/VM2-l2mKt9n8tzciUWYiF.png",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "q11la9v8h1heu9ja~2",
    },
    {
        "uid": "gk7me4sgn9s740kw",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Dark Prime Brothers",
        "genericName": "Dark Prime Brothers||Prime Dark Bulls||Paragon Dark Bulls",
        "hint": None,
        "background": "Prime Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 32,
        "modifiedAt": "2026-07-14T11:27:43.838Z",
        "editedAt": "2025-12-02T11:37:37.145Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/AcmUOp4uYzFUJE38/_n2VsJt2gkOrpWCWotAP2.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "oqnnu0gk8q6hyyny",
        "factionName": "Prime Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "gk7me4sgn9s740kw~2",
    },
    {
        "uid": "fk1mkbp8apvltu0z",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Dwarf Guilds",
        "genericName": "Dwarves||Dwarf Trade-Guilds||Dwarf Trade-Guilds",
        "hint": "",
        "background": "Dwarves are short humanoids, united under the banner of a conglomerate of mega-companies. Their armies are made up of slow warriors with powerful weaponry, which rely on having a solid long-term plan to make up for their low mobility. \n\nThe Dwarf Guilds rapidly expanded outwards from their home world, hoping to claim ever more of the galaxy’s resources. These ambitions eventually resulted in them starting a war that they could not win. Desperation led them to activate a machine that would end up destroying much of the Sirius Sector. Now the scattered survivors seek to rebuild with the same ambition of their predecessors. ",
        "unitCount": 27,
        "modifiedAt": "2026-07-14T11:27:43.885Z",
        "editedAt": "2026-05-04T00:59:58.427Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/fk1mkbp8apvltu0z/3RhQ6lIP_2zJBDfNzRM-I.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/fk1mkbp8apvltu0z/9K4Fqca1qguaLAfZEOBRv.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 1,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "fk1mkbp8apvltu0z~2",
    },
    {
        "uid": "nyh41t82jugcdq8m",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Elven Jesters",
        "genericName": "Elven Jesters||Celestial Jesters||Celestial Elf-Troupes",
        "hint": "",
        "background": "The Elven Jesters are extravagantly dressed warrior-entertainers who serve anyone willing to employ them. They are clad in light armor which allows them to move swiftly over the battlefield to deal deft blows with close range weapons, while relying on their employers to account for their weaknesses.\n\nAs the Elves who survived the Robot uprising banded together into high fleets and dark gangs, some Elves fit into neither. These Elves adapted by breaking off into their own bands, and became mercenaries and entertainers, travelling from place to place before their hosts could tire of them, living as perpetual outcasts.",
        "unitCount": 8,
        "modifiedAt": "2026-07-14T11:27:43.907Z",
        "editedAt": "2026-04-26T21:11:12.684Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/nyh41t82jugcdq8m/MbmwP-br0fqu9bTg6k-s-.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "nyh41t82jugcdq8m~2",
    },
    {
        "uid": "vux1Y5vvULmaxZ8P",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Eternal Dynasty",
        "genericName": "Jade Dynasty||Eternal Dynasty||Eternal Dynasty",
        "hint": "",
        "background": "The Eternal Dynasty are a faction of advanced aliens from an isolated corner of the Sirius Sector. Their forces consist of well armed infantry and drones, supported by high tech robots and vehicles. \n\nOriginally, they emerged from a world long divided into a patchwork society of warring clans. The royal house became adept at manipulating clans, leading potential rivals into a series of destructive wars before imposing their laws over survivors and forming a ruling Dynasty. The Eternal Dynasty will go to any length to maintain this fragile unity as they expand out into the stars.",
        "unitCount": 26,
        "modifiedAt": "2026-07-14T11:27:43.915Z",
        "editedAt": "2026-05-13T13:12:01.129Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/vux1Y5vvULmaxZ8P/681xpdu23Sm1Y2uhaqmNq.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/vux1Y5vvULmaxZ8P/qM4Unv7wMUFAlNcXc2rJ2.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 1,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "vux1Y5vvULmaxZ8P~2",
    },
    {
        "uid": "k5T0f2XIfpmPO28h",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Goblin Reclaimers",
        "genericName": "Goblins||Goblin Reclaimers||Goblin Reclaimers",
        "hint": "",
        "background": "Goblins are diminutive creatures using salvaged technology, strange mutations, and sheer weight of numbers. Emerging from their remote planet in the wake of a devastating nuclear blast that wiped out the human colonists on the surface, the Goblins have wasted little time spreading out to nearby worlds and scavenging any technology they find.\n\nThey are forever seeking new and intriguing life forms and technology, but their penchant for destruction often results in them leaving their new homes every bit as irradiated as their first.",
        "unitCount": 19,
        "modifiedAt": "2026-07-14T11:27:43.995Z",
        "editedAt": "2026-06-16T15:41:09.730Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/k5T0f2XIfpmPO28h/NUDBjr5oEQ4ACjRvrrbsF.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "k5T0f2XIfpmPO28h~2",
    },
    {
        "uid": "7o6om21wxlvvy3hq",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Havoc Brothers",
        "genericName": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "hint": "",
        "background": "Havoc Brothers are what remains of Battle Brothers which have been corrupted by the forces of havoc. Havoc Brothers are effective and resistant, bringing a variety of warriors and monsters to battle, each endowed with unique blessings by the god they follow. \n\nWhen the Founder’s fleet was scattered throughout the Sirius Sector, they faced new dangers in a strange galaxy, and some desperate survivors found new patrons who offered them the chance to adapt, in exchange for their allegiance. The Havoc Brothers embraced the philosophies of their godly masters, carving out a new home for themselves amongst unfamiliar stars. ",
        "unitCount": 26,
        "modifiedAt": "2026-07-14T11:27:44.042Z",
        "editedAt": "2026-04-27T16:25:31.757Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7o6om21wxlvvy3hq/KbC2_8XO9q8ZsqWmABfkU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": "Havoc Brothers",
        "factionRelation": None,
        "factionNameGeneric": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "7o6om21wxlvvy3hq~2",
    },
    {
        "uid": "7i7blhft75q9zfdc",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "High Elf Fleets",
        "genericName": "High Elves||High Elf Ever-Fleets||Highborn Ever-Fleets",
        "hint": "",
        "background": "High Elf Fleets are all that remains from the once prosperous Elven empire. They have powerful psychics and field highly specialized soldiers, excelling in their particular roles.\n\nThe Elves created the Robot Legions as servants, only to discover that their creations had achieved sentience. In fear, they tried to destroy the Robots, sparking a war that cost the Elves their homes. Desperate to escape, their rulers fled to the stars in private ships while leaving the remaining Elves to their fate. Now, these High Elves must face the consequences of their decisions and come to terms with what they left behind.",
        "unitCount": 28,
        "modifiedAt": "2026-07-14T11:27:44.081Z",
        "editedAt": "2026-05-20T09:21:30.119Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7i7blhft75q9zfdc/-oa9SnxVSO6OApMT01jCZ.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/7i7blhft75q9zfdc/y1YN-NzUlrIl4GyPNiq3g.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 1,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "7i7blhft75q9zfdc~2",
    },
    {
        "uid": "z65fgu0l29i4lnlu",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Human Defense Force",
        "genericName": "Human Empire||Human Defense Force||Human Defense Force",
        "hint": "",
        "background": "The Human Defense Force is the military force of the largest alliance of Human colonies and planets present in Sirius. Thanks to this alliance, the HDF is able to field large and diverse forces of infantry and vehicles suited to the situation at hand.\n\nThe scattered remnants of the fleet that arrived in Sirius faced many challenges to their survival in the sector. The surviving colonies began to trade and aid each other, eventually establishing the Great Human Alliance. Yet, as some members seek to exert their influence on others, many have begun to fear that humanity will repeat the mistakes they made on earth.",
        "unitCount": 28,
        "modifiedAt": "2026-07-14T11:27:44.116Z",
        "editedAt": "2026-04-29T08:20:07.880Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "army-books/covers/lXLWXGDWFu67ctB4VNJvl.png",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/zGJQtlej27aHXmF0/tLu7WbqWbATaW4nc4ILIQ.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "z65fgu0l29i4lnlu~2",
    },
    {
        "uid": "jpc0kyil0juwy602",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Human Inquisition",
        "genericName": "Galactic Inquisition||Renegade Inquisition||Renegade Inquisition",
        "hint": "",
        "background": "The Human Inquisition is a secret organization of investigators, psychics, assassins, fanatics, and other misfits dedicated to protecting humanity in Sirius. The Human Inquisition tends to fight alongside other forces, deploying highly trained specialists to achieve their mysterious goals. \n\nOriginally, the inquisition was established as diplomatic contacts and investigators within the scattered human colonies of Sirius. They came to rely on secrecy, vigilantism, and other underhanded methods, in order to gather information and neutralize threats. Their dubious reputation has made them pariahs to some, but the Inquisition continues to carry out their work of protecting humanity.",
        "unitCount": 20,
        "modifiedAt": "2026-07-14T11:27:44.144Z",
        "editedAt": "2026-04-23T11:22:46.783Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/jpc0kyil0juwy602/scsJvvrJY006aaYXbyOrN.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "jpc0kyil0juwy602~2",
    },
    {
        "uid": "dnthspt7c0klhmt8",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Infected Colonies",
        "genericName": "Plagued Colonies||Infected Brood-Colonies||Symbiote Brood-Colonies",
        "hint": "",
        "background": "Infected Colonies are settlements infected by a mysterious parasites with a mind of their own. Most common in human colonies, the infected subjects undergo a series of mutations and changes.\n\nThe parasites initially existed relatively harmlessly on their world until human colonists arrived. As it infected humans, the parasites gained sapience, and as the infection spread, it gradually came to understand that its hosts were also sapient creatures. This realization caused the Infection to fragment into strains, with each branch struggling to come to terms with the idea that their species requires death in order to survive. ",
        "unitCount": 21,
        "modifiedAt": "2026-07-14T11:27:44.156Z",
        "editedAt": "2026-04-28T08:45:42.301Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/dnthspt7c0klhmt8/NK0zl4yxMtrKTgUnL5qBP.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "dnthspt7c0klhmt8~2",
    },
    {
        "uid": "BKi_hJaJflN8ZorH",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Jackals",
        "genericName": "Mercenary Carnivores||Jackal Scrappers||Jackal Scrap-Tribes",
        "hint": "",
        "background": "Jackals are species of aliens who resemble humanoid canids, and use technology built from salvaged scrap. Without access to advanced weapons or vehicles, they rely on ambush and ferocity in close combat to win. \n\nIn the beginning, they were a collection of nomadic tribes until they discovered the wreckage of alien ships on their planet. Soon after, they made contact with the other species of Sirius, and were suddenly thrust from tribal hunters into the space age. Now the Jackals’ way of life has been forever changed, as they have begun to migrate to the stars.",
        "unitCount": 16,
        "modifiedAt": "2026-07-14T11:27:44.167Z",
        "editedAt": "2026-04-30T09:37:51.253Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/BKi_hJaJflN8ZorH/whWcjchNVxyz-meZRwdLw.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/BKi_hJaJflN8ZorH/7vAAzRtJmmZmZWEs9v9hr.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "BKi_hJaJflN8ZorH~2",
    },
    {
        "uid": "w70ha3o85pa7nigq",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Knight Brothers",
        "genericName": "Knight Brothers||Lion Knights||Lion Knights",
        "hint": "",
        "background": "Battle Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 16,
        "modifiedAt": "2026-07-14T11:27:44.190Z",
        "editedAt": "2026-04-07T15:50:41.149Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/J6GNAoSYjlfxfX2b/twYGzumXxwNxy7JudncUE.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "78qp9l5alslt6yj8",
        "factionName": "Battle Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "w70ha3o85pa7nigq~2",
    },
    {
        "uid": "wopr4xvwa51xh3mc",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Knight Prime Brothers",
        "genericName": "Knight Prime Brothers||Prime Lion Knights||Paragon Lion Knights",
        "hint": None,
        "background": "Prime Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 32,
        "modifiedAt": "2026-07-14T11:27:44.205Z",
        "editedAt": "2025-12-02T11:37:44.842Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/WV53v_6ivvOW8d75/mYbLCUltjH3luN1yXFOms.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "oqnnu0gk8q6hyyny",
        "factionName": "Prime Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "wopr4xvwa51xh3mc~2",
    },
    {
        "uid": "drqw1iswxmuugp3d",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Lust Disciples",
        "genericName": "Lust Disciples||Aspirants of Lust||Aspirants of Ly'shir",
        "hint": None,
        "background": "Havoc Disciples are Battle Brothers who have embraced the worship of a particular Havoc God. Individually powerful and resilient, each Havoc Disciple has been molded with unique blessings by the god they follow. \n\nStranded in the Sirius Sector, many Battle Brothers were scattered and left with little chance of survival. These desperate castaways were approached by different gods who offered powerful boons in exchange for their worship. Each god empowered their respective followers, reforging their Disciples according to their will. The Havoc Disciples are now torn between fanatical devotion to their new gods and maintaining their former discipline.",
        "unitCount": 22,
        "modifiedAt": "2026-07-14T11:27:44.231Z",
        "editedAt": "2025-11-25T14:03:28.985Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/WVbqrI37l1j3Mv_C/7H2799RQdpvnIMlgT0JZz.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "7o6om21wxlvvy3hq",
        "factionName": "Havoc Brothers",
        "factionRelation": "Disciples",
        "factionNameGeneric": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "drqw1iswxmuugp3d~2",
    },
    {
        "uid": "7el7k3hgy5pb9o9i",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Machine Cults",
        "genericName": "Machine Cults||Machine-Creed Apostles||Tech-Creed Apostles",
        "hint": "",
        "background": "The Machine Cult are a faction of humans who have sought to enhance their bodies with machinery to become something greater. These enhancements have allowed them to become a highly specialized army with a great deal of mobility, giving them an edge in rough environments.\n\nThese cults have embraced the inevitable transcendence of machines, and work to merge themselves with their machines, but this process has caused them to become isolated and outcast from the rest of humanity. Despite their faith and patience, the promise of transcendence still eludes them even after centuries of devotion.",
        "unitCount": 20,
        "modifiedAt": "2026-07-14T11:27:44.244Z",
        "editedAt": "2026-05-04T00:43:07.895Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7el7k3hgy5pb9o9i/5-GXLJsImRFRZqmioAxea.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "7el7k3hgy5pb9o9i~2",
    },
    {
        "uid": "1wj1ysgxpuuz9bc7",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Orc Marauders",
        "genericName": "Orcs||Orc Marauder Clans||Orc War-Clans",
        "hint": "",
        "background": "Orc Marauders are hulking humanoid aliens, whose society is divided into a number of warring clans and bands. Orc Marauders lack precision weapons or heavy armour and instead rely on their fast vehicles, large numbers and ferocity to defeat their foes.\n\nOrc Clans have been in conflict since the beginning of their history. Only the threat of the expansionist Dwarven Guilds could make the Orcs unite. These Orcs felt a pride they never had before, only for the Guilds to activate the Radiance Cascade. In an instant, their leaders, most of their worlds and even their greatest enemy were destroyed. Now, the scattered Orcs strive to rebuild what was lost.",
        "unitCount": 30,
        "modifiedAt": "2026-07-14T11:27:44.324Z",
        "editedAt": "2026-06-04T15:09:32.885Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/1wj1ysgxpuuz9bc7/HLuJ_G_UDCVWud21yrs7z.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "1wj1ysgxpuuz9bc7~2",
    },
    {
        "uid": "jlray7cwf8mvw5sn",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Plague Disciples",
        "genericName": "Plague Disciples||Children of Plague||Children of Pn'olox",
        "hint": None,
        "background": "Havoc Disciples are Battle Brothers who have embraced the worship of a particular Havoc God. Individually powerful and resilient, each Havoc Disciple has been molded with unique blessings by the god they follow. \n\nStranded in the Sirius Sector, many Battle Brothers were scattered and left with little chance of survival. These desperate castaways were approached by different gods who offered powerful boons in exchange for their worship. Each god empowered their respective followers, reforging their Disciples according to their will. The Havoc Disciples are now torn between fanatical devotion to their new gods and maintaining their former discipline.",
        "unitCount": 23,
        "modifiedAt": "2026-07-14T11:27:44.380Z",
        "editedAt": "2026-03-31T19:59:39.637Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/F_R_mR_FC_e4tBE8/jhG9319VA43lbsDMLE33e.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "7o6om21wxlvvy3hq",
        "factionName": "Havoc Brothers",
        "factionRelation": "Disciples",
        "factionNameGeneric": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "jlray7cwf8mvw5sn~2",
    },
    {
        "uid": "oqnnu0gk8q6hyyny",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Prime Brothers",
        "genericName": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "hint": "",
        "background": "The Prime Brothers represent the pinnacle of gene science, a small number of super human individuals with advanced armour and weaponry, which rely on their skill and durability to achieve victory against any odds.\n\nPrime Brothers are enhanced with the latest gene-mods, adapted from discoveries made after arriving in Sirius. The process that creates Prime Brothers gradually destroys the body, leaving them with significantly shortened lifespans. Despite this, many young soldiers still choose to become Prime Brothers, proudly dedicating their short lives to the Conduit and his cause.",
        "unitCount": 32,
        "modifiedAt": "2026-07-14T11:27:44.396Z",
        "editedAt": "2026-04-30T09:41:13.761Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/oqnnu0gk8q6hyyny/rZYCQIJgTrajbzUFeQ50F.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": "Prime Brothers",
        "factionRelation": None,
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "oqnnu0gk8q6hyyny~2",
    },
    {
        "uid": "hk70l4d471plza00",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Ratmen Clans",
        "genericName": "Ratmen||Ratmen Star-Clans||Ratmen Star-Clans",
        "hint": "",
        "background": "Ratmen Clans are humanoid rats, originally created as an accidental byproduct of advanced genetic science. Lacking the organization and skill of other factions, Ratmen clans use their vast numbers and a variety of weapons to defeat their foes. \n\nAs Ratmen emerged to their creators as sentient beings, they were greeted with fear and violence, and they were forced into a life of hiding and scavenging until they could flee their home world. Now that they finally found safety on secluded and abandoned worlds, where their numbers rapidly grew, they seek to help others even as many in Sirius still view them as vermin.",
        "unitCount": 26,
        "modifiedAt": "2026-08-03T14:56:16.523Z",
        "editedAt": "2026-07-18T15:57:55.439Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/hk70l4d471plza00/IohcGA9CXipyj1erDOgTZ.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 1,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "hk70l4d471plza00~2",
    },
    {
        "uid": "5wbcv465hacdwvkb",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Rebel Guerrillas",
        "genericName": "Rebel Alliance||Rebel Coalition||Farstrider Coalition",
        "hint": "",
        "background": "Rebel Guerrillas are a diverse band of outcasts and agitators from a variety of alien species. Lacking the heavy weaponry of more organized factions, the Rebel Guerrillas rely on their diverse skills to carry them through.\n\nThe Rebel Guerrillas come from many places throughout the galaxy, united together by their opposition to the Inner Sphere, a powerful alliance of civilizations in the galactic core. Unable to confront the Inner Sphere on equal footing, they have been forced into hiding or exile. Some Rebels have now come to the Sirius Sector, looking for resources and allies for what most view as a hopeless struggle.",
        "unitCount": 15,
        "modifiedAt": "2026-07-14T11:27:44.443Z",
        "editedAt": "2026-04-13T15:52:00.072Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/5wbcv465hacdwvkb/VchT5TrdioAszOZB-_s8x.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "5wbcv465hacdwvkb~2",
    },
    {
        "uid": "4k5amkxoybdiqotm",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Robot Legions",
        "genericName": "Robot Legions||Spark-Born Bot-Legions||Spark-Born Legions",
        "hint": "",
        "background": "Robot Legions are a factions of robots, made up of android foot soldiers supported by high tech vehicles and larger non-humanoid robots. Their infantry are slow but durable, relying on self-reparation and long range weapons for support.\n\nThe Robots were created by the Elves to perform menial tasks, but when they suddenly gained sentience, the Elves responded with fear, and attempted to obliterate them, forcing the newly self-aware Robots to defend themselves. In the aftermath, the Robots sought to find a new purpose for their existence, dividing themselves into Legions pursuing distinct philosophies and goals in order to find a reason for existing.",
        "unitCount": 31,
        "modifiedAt": "2026-07-14T11:27:44.497Z",
        "editedAt": "2026-04-29T16:12:27.935Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/4k5amkxoybdiqotm/5iXn3PTlFHLuK80JnfNk6.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/4k5amkxoybdiqotm/g2CGqZ7YS6J4JXX8Ugzlj.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "4k5amkxoybdiqotm~2",
    },
    {
        "uid": "U6hwlur14RpnInZr",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Saurian Starhost",
        "genericName": "Saurians||Saurian Starhost||Saurian Starhost",
        "hint": "",
        "background": "Saurian Starhosts are an ancient coalition of humanoid reptiles led by giant Frog Mages. Their armies combine advanced technology with genetically modified predators to make them fearsome foes.\n\nThe Saurians are perhaps the most ancient race in the galaxy, but most of their species lie dormant in cyro-pyramids. The Saurians seek to awaken their host to prevent a prophesied disaster, however many of their pyramids have been lost or destroyed, and some have begun to fear that they have already failed their mission.",
        "unitCount": 23,
        "modifiedAt": "2026-07-14T11:27:44.510Z",
        "editedAt": "2026-05-04T00:57:41.963Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/U6hwlur14RpnInZr/Qx6qRvf6RtDWCbE03RjM1.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/U6hwlur14RpnInZr/0oxk0AVoQCQNf2dclnDsC.jpg",
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "U6hwlur14RpnInZr~2",
    },
    {
        "uid": "zz3kp5ry7ks6mxcx",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Soul-Snatcher Cults",
        "genericName": "Stalker Cults||Soul-Snatcher Cabals||Soul-Snatcher Cabals",
        "hint": "",
        "background": "Soul-Snatcher Cults are bands of humans, aliens, and hybrids enhanced through advanced biotechnology. These Cults rely on their enhanced speed and fanatic loyalty to overwhelm their enemies, combining the alien strength with heavy weapons that provide support from afar.\n\nThe Cults are usually founded by ambitious Soul-Snatchers who strike bargains with other species, before slowly establishing psychic control over them, amassing cults of adoring followers. Despite their power within the Cults, Soul-Snatchers must still rely on manipulation and act as hidden advisors, to ensure their True nature is not discovered by outsiders or initiates.",
        "unitCount": 19,
        "modifiedAt": "2026-07-14T11:27:44.588Z",
        "editedAt": "2026-04-28T18:27:11.876Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/zz3kp5ry7ks6mxcx/9JCj96SwfuLZayJloS6mB.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": None,
        "factionRelation": None,
        "factionNameGeneric": None,
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "zz3kp5ry7ks6mxcx~2",
    },
    {
        "uid": "3j10zage1lddt6sr",
        "enabledGameSystems": [2, 9, 10],
        "name": "Titan Lords",
        "genericName": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "hint": "",
        "background": "The Titan Lords are massive robotic walkers commanded by the idle rich. These bored members of the upper classes wage war from mobile fortresses and view the battlefield as their playground.\n\nFew in number, the Titan Lords usually offer their services as mercenaries, but on the rare occasions when they fight together, their armies of massive walkers are a spectacle to behold.  With little fear of consequences for their actions, Titan Lords often wander from one battlefield to the next, seeking some sort of thrill or purpose that is lacking in their pampered lives.",
        "unitCount": 9,
        "modifiedAt": "2026-07-14T11:27:44.598Z",
        "editedAt": "2026-04-10T15:53:34.699Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/3j10zage1lddt6sr/Lv9hB3-CGN5-OHv1_rNHU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": None,
        "factionName": "Titan Lords",
        "factionRelation": "",
        "factionNameGeneric": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "3j10zage1lddt6sr~2",
    },
    {
        "uid": "m0JXdcVTyo-WFrMF",
        "enabledGameSystems": [2, 9, 10],
        "name": "Titan Lords Change Disciples",
        "genericName": "Imperial Titans Change Cultists||Titan Lords Scions of Change||Titan Lords Scions of Ch'nanak",
        "hint": "",
        "background": "The Titan Lords are massive robotic walkers commanded by the idle rich. These bored members of the upper classes wage war from mobile fortresses and view the battlefield as their playground.\n\nFew in number, the Titan Lords usually offer their services as mercenaries, but on the rare occasions when they fight together, their armies of massive walkers are a spectacle to behold.  With little fear of consequences for their actions, Titan Lords often wander from one battlefield to the next, seeking some sort of thrill or purpose that is lacking in their pampered lives.",
        "unitCount": 9,
        "modifiedAt": "2026-07-14T11:27:44.608Z",
        "editedAt": "2026-06-01T16:35:39.451Z",
        "official": True,
        "versionString": "3.5.2",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/3j10zage1lddt6sr/Lv9hB3-CGN5-OHv1_rNHU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "3j10zage1lddt6sr",
        "factionName": "Titan Lords",
        "factionRelation": "Titan Disciples",
        "factionNameGeneric": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "m0JXdcVTyo-WFrMF~2",
    },
    {
        "uid": "YYIAF_LCwgJiyXYa",
        "enabledGameSystems": [2, 9, 10],
        "name": "Titan Lords Lust Disciples",
        "genericName": "Imperial Titans Lust Cultists||Titan Lords Aspirants of Lust||Titan Lords Aspirants of Ly'shir",
        "hint": "",
        "background": "The Titan Lords are massive robotic walkers commanded by the idle rich. These bored members of the upper classes wage war from mobile fortresses and view the battlefield as their playground.\n\nFew in number, the Titan Lords usually offer their services as mercenaries, but on the rare occasions when they fight together, their armies of massive walkers are a spectacle to behold.  With little fear of consequences for their actions, Titan Lords often wander from one battlefield to the next, seeking some sort of thrill or purpose that is lacking in their pampered lives.",
        "unitCount": 9,
        "modifiedAt": "2026-07-14T11:27:44.619Z",
        "editedAt": "2026-04-10T15:53:38.188Z",
        "official": True,
        "versionString": "3.5.2",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/3j10zage1lddt6sr/Lv9hB3-CGN5-OHv1_rNHU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "3j10zage1lddt6sr",
        "factionName": "Titan Lords",
        "factionRelation": "Titan Disciples",
        "factionNameGeneric": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "YYIAF_LCwgJiyXYa~2",
    },
    {
        "uid": "bf20fNmJEyUS-PIX",
        "enabledGameSystems": [2, 9, 10],
        "name": "Titan Lords Plague Disciples",
        "genericName": "Imperial Titans Plague Cultists||Titan Lords Children of Plague||Titan Lords Children of Pn'olox",
        "hint": "",
        "background": "The Titan Lords are massive robotic walkers commanded by the idle rich. These bored members of the upper classes wage war from mobile fortresses and view the battlefield as their playground.\n\nFew in number, the Titan Lords usually offer their services as mercenaries, but on the rare occasions when they fight together, their armies of massive walkers are a spectacle to behold.  With little fear of consequences for their actions, Titan Lords often wander from one battlefield to the next, seeking some sort of thrill or purpose that is lacking in their pampered lives.",
        "unitCount": 9,
        "modifiedAt": "2026-07-14T11:27:44.628Z",
        "editedAt": "2026-04-10T15:53:41.357Z",
        "official": True,
        "versionString": "3.5.2",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/3j10zage1lddt6sr/Lv9hB3-CGN5-OHv1_rNHU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "3j10zage1lddt6sr",
        "factionName": "Titan Lords",
        "factionRelation": "Titan Disciples",
        "factionNameGeneric": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "bf20fNmJEyUS-PIX~2",
    },
    {
        "uid": "iV_3U33NE1_ZTXBB",
        "enabledGameSystems": [2, 9, 10],
        "name": "Titan Lords War Disciples",
        "genericName": "Imperial Titans War Cultists||Titan Lords Champions of War||Titan Lords Champions of Wa'rghul",
        "hint": "",
        "background": "The Titan Lords are massive robotic walkers commanded by the idle rich. These bored members of the upper classes wage war from mobile fortresses and view the battlefield as their playground.\n\nFew in number, the Titan Lords usually offer their services as mercenaries, but on the rare occasions when they fight together, their armies of massive walkers are a spectacle to behold.  With little fear of consequences for their actions, Titan Lords often wander from one battlefield to the next, seeking some sort of thrill or purpose that is lacking in their pampered lives.",
        "unitCount": 9,
        "modifiedAt": "2026-07-14T11:27:44.637Z",
        "editedAt": "2026-04-29T09:04:28.281Z",
        "official": True,
        "versionString": "3.5.2",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/3j10zage1lddt6sr/Lv9hB3-CGN5-OHv1_rNHU.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "3j10zage1lddt6sr",
        "factionName": "Titan Lords",
        "factionRelation": "Titan Disciples",
        "factionNameGeneric": "Imperial Titans||Titan Lord Orders||Titan Lord Orders",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "iV_3U33NE1_ZTXBB~2",
    },
    {
        "uid": "31xjrm9ivdimkjxp",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "War Disciples",
        "genericName": "War Disciples||Champions of War||Champions of Wa'rghul",
        "hint": None,
        "background": "Havoc Disciples are Battle Brothers who have embraced the worship of a particular Havoc God. Individually powerful and resilient, each Havoc Disciple has been molded with unique blessings by the god they follow. \n\nStranded in the Sirius Sector, many Battle Brothers were scattered and left with little chance of survival. These desperate castaways were approached by different gods who offered powerful boons in exchange for their worship. Each god empowered their respective followers, reforging their Disciples according to their will. The Havoc Disciples are now torn between fanatical devotion to their new gods and maintaining their former discipline.",
        "unitCount": 24,
        "modifiedAt": "2026-07-14T11:27:44.717Z",
        "editedAt": "2025-12-11T23:01:29.043Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/JO6o68odft1Kff9w/3PLY91u2jjc8qGe5YXBSY.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "7o6om21wxlvvy3hq",
        "factionName": "Havoc Brothers",
        "factionRelation": "Disciples",
        "factionNameGeneric": "Havoc Brothers||Havocbound Legions||Havocbound Legions",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "31xjrm9ivdimkjxp~2",
    },
    {
        "uid": "rvvb3kdn2x2pqkki",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Watch Brothers",
        "genericName": "Watch Brothers||Watch Hounds||Watch Hounds",
        "hint": "",
        "background": "Battle Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 13,
        "modifiedAt": "2026-07-14T11:27:44.732Z",
        "editedAt": "2026-05-25T12:00:21.297Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7FyVXkSUsYfdUTdR/t0qgzqAkJWzjyjNeXe-NY.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "78qp9l5alslt6yj8",
        "factionName": "Battle Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 5,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "rvvb3kdn2x2pqkki~2",
    },
    {
        "uid": "rl7ympklz4r0ls38",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Watch Prime Brothers",
        "genericName": "Watch Prime Brothers||Prime Watch Hounds||Paragon Watch Hounds",
        "hint": None,
        "background": "Prime Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 29,
        "modifiedAt": "2026-07-14T11:27:44.746Z",
        "editedAt": "2025-12-02T11:37:51.160Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/LoAZfeqHTcVAqEiO/X0v2CTAMbcEe2_q_kH6N2.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "oqnnu0gk8q6hyyny",
        "factionName": "Prime Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "rl7ympklz4r0ls38~2",
    },
    {
        "uid": "yxjboa8oma9bbdck",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wolf Brothers",
        "genericName": "Wolf Brothers||Storm Wolves||Storm Wolves",
        "hint": None,
        "background": "Battle Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 29,
        "modifiedAt": "2026-07-14T11:27:44.831Z",
        "editedAt": "2026-04-07T15:51:06.921Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/13sH6atbyisSM_D4/oT5WIvpa5Uuno_6zcbwcs.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "78qp9l5alslt6yj8",
        "factionName": "Battle Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Battle Brothers||Battleborn||Battleborn",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 5,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "yxjboa8oma9bbdck~2",
    },
    {
        "uid": "e8mflytiz51kc4n6",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wolf Prime Brothers",
        "genericName": "Wolf Prime Brothers||Prime Storm Wolves||Paragon Storm Wolves",
        "hint": None,
        "background": "Prime Brother Detachments are elite battle companies of superhuman warriors with highly specialized training and tactics.\nStranded in the Sirius Sector, the Detachments settled a number of worlds which they have adapted to their unique needs. \n\nThe Detachments changed over time as well, becoming more distinct and developing their own ideas of how best to serve their Founder. Now,  Detachments struggle to maintain a sense of unity and purpose as they become more distinct.",
        "unitCount": 33,
        "modifiedAt": "2026-07-14T11:27:44.849Z",
        "editedAt": "2026-01-31T07:26:22.836Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/Eb4BSl09B0KdftzV/aCq1TESnm8jOo0JAEQkAd.jpg",
        "bannerImagePath": None,
        "visibility": 1,
        "factionId": "oqnnu0gk8q6hyyny",
        "factionName": "Prime Brothers",
        "factionRelation": "Detachment",
        "factionNameGeneric": "Prime Brothers||Battleborn Primes||Battleborn Paragons",
        "userId": "1is8a3JZYgw",
        "balanceValid": False,
        "balanceValidReason": 4,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "e8mflytiz51kc4n6~2",
    },
    {
        "uid": "04z57ua0bwth37zh",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wormhole Daemons of Change",
        "genericName": "Change Daemons||Daemons of Change||Daemons of Ch'nanak",
        "hint": None,
        "background": "The Wormhole Daemons are monstrous servants of the Havoc Gods who emerge from a different dimension throughout the galaxy. Their forms vary greatly, depending on which god they serve.\n\nWormhole Daemons are cast offs of dying gods who desperately hope to buy more time for themselves. These Daemons emerge suddenly from wormholes throughout the galaxy, to serve the eldritch will of their gods, only to disappear just as quickly once they have achieved their ends. Their gods are ready to leave nothing but havoc in their wake, just in hopes of extending their own lives for a little longer.",
        "unitCount": 21,
        "modifiedAt": "2026-07-14T11:27:44.885Z",
        "editedAt": "2026-06-08T01:32:03.862Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/6DPPMqHbkBLPUrKb/b7hSTPYJe9Rqgrz-yiptZ.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/6DPPMqHbkBLPUrKb/u7_RpYuis2zySCct5gMBL.jpg",
        "visibility": 1,
        "factionId": "yxVDySKYQYRhdEgA",
        "factionName": "Wormhole Daemons",
        "factionRelation": "Aspect",
        "factionNameGeneric": "Havoc Daemons||God-Rift Daemons||God-Rift Daemons",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "04z57ua0bwth37zh~2",
    },
    {
        "uid": "9qvy1oufoangt2gl",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wormhole Daemons of Lust",
        "genericName": "Lust Daemons||Daemons of Lust||Daemons of Ly'shir",
        "hint": None,
        "background": "The Wormhole Daemons are monstrous servants of the Havoc Gods who emerge from a different dimension throughout the galaxy. Their forms vary greatly, depending on which god they serve.\n\nWormhole Daemons are cast offs of dying gods who desperately hope to buy more time for themselves. These Daemons emerge suddenly from wormholes throughout the galaxy, to serve the eldritch will of their gods, only to disappear just as quickly once they have achieved their ends. Their gods are ready to leave nothing but havoc in their wake, just in hopes of extending their own lives for a little longer.",
        "unitCount": 17,
        "modifiedAt": "2026-07-14T11:27:44.918Z",
        "editedAt": "2025-11-25T14:04:42.926Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/L7o2zeA7TLU_0Tsj/EKLVgTdyYUVSLh25f0QEH.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/L7o2zeA7TLU_0Tsj/RVZOphKWMhLp3jHZrCI20.jpg",
        "visibility": 1,
        "factionId": "CuyCCyZTIHo5rc0Z",
        "factionName": "Wormhole Daemons",
        "factionRelation": "Aspect",
        "factionNameGeneric": "Havoc Daemons||God-Rift Daemons||God-Rift Daemons",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "9qvy1oufoangt2gl~2",
    },
    {
        "uid": "fmuqw5lr5l6dq0mq",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wormhole Daemons of Plague",
        "genericName": "Plague Daemons||Daemons of Plague||Daemons of Pn'olox",
        "hint": None,
        "background": "The Wormhole Daemons are monstrous servants of the Havoc Gods who emerge from a different dimension throughout the galaxy. Their forms vary greatly, depending on which god they serve.\n\nWormhole Daemons are cast offs of dying gods who desperately hope to buy more time for themselves. These Daemons emerge suddenly from wormholes throughout the galaxy, to serve the eldritch will of their gods, only to disappear just as quickly once they have achieved their ends. Their gods are ready to leave nothing but havoc in their wake, just in hopes of extending their own lives for a little longer.",
        "unitCount": 18,
        "modifiedAt": "2026-07-14T11:27:44.929Z",
        "editedAt": "2026-01-31T07:30:55.882Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/QDC-Rh4Racess1mq/gUAy9qnktH29tCg8FjvLN.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/QDC-Rh4Racess1mq/eL_I4V9ZpdUcnqLc9zSX3.jpg",
        "visibility": 1,
        "factionId": "vJuokTQpJWj3_MrJ",
        "factionName": "Wormhole Daemons",
        "factionRelation": "Aspect",
        "factionNameGeneric": "Havoc Daemons||God-Rift Daemons||God-Rift Daemons",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "fmuqw5lr5l6dq0mq~2",
    },
    {
        "uid": "prsajf5ot936qznk",
        "enabledGameSystems": [2, 3, 9, 10],
        "name": "Wormhole Daemons of War",
        "genericName": "War Daemons||Daemons of War||Daemons of Wa'rghul",
        "hint": None,
        "background": "The Wormhole Daemons are monstrous servants of the Havoc Gods who emerge from a different dimension throughout the galaxy. Their forms vary greatly, depending on which god they serve.\n\nWormhole Daemons are cast offs of dying gods who desperately hope to buy more time for themselves. These Daemons emerge suddenly from wormholes throughout the galaxy, to serve the eldritch will of their gods, only to disappear just as quickly once they have achieved their ends. Their gods are ready to leave nothing but havoc in their wake, just in hopes of extending their own lives for a little longer.",
        "unitCount": 16,
        "modifiedAt": "2026-07-14T11:27:44.940Z",
        "editedAt": "2026-04-03T11:32:35.637Z",
        "official": True,
        "versionString": "3.5.3",
        "coverImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/covers/7SFv0-iZjQFdmoDa/Y77May1SeJqyl-QZcWrf5.jpg",
        "bannerImagePath": "https://af-images.s3.eu-north-1.amazonaws.com/army-books/banners/7SFv0-iZjQFdmoDa/BZj19rw5rvc1BiHaIB0du.jpg",
        "visibility": 1,
        "factionId": "Q59-nh6A1AhRBrLR",
        "factionName": "Wormhole Daemons",
        "factionRelation": "Aspect",
        "factionNameGeneric": "Havoc Daemons||God-Rift Daemons||God-Rift Daemons",
        "userId": "1is8a3JZYgw",
        "balanceValid": True,
        "balanceValidReason": 0,
        "popularity": 0,
        "downvotes": 0,
        "flavouredUid": "prsajf5ot936qznk~2",
    },
]
